### PR TITLE
Add received_at_millis_since_epoch

### PR DESCRIPTION
**Pull request by orborde**
Soon, we'll plumb this through MAD and CAGG in order to instrument the end-to-end pipeline latency,

### CODE REVIEW

**Review by BrandonArp — CHANGES_REQUESTED** [review]
I'm not a fan of the name received_at

**Comment by vjkoskela** [comment]
That was my first reaction as well. However, I couldn’t really come up with anything better. Any suggestions?

The field represents the time the client transmitting code received the measurement, which is sometime after the start and end time.

If we want to switch the perspective we could swap it to transmitted_at although that has a very clear definition (which may be a good thing) and is a bit off when you consider retries and the like.

There are other vague options like processes_at.

In the end, at this point I believe the time should be set after the data is pulled from the client queue and transmission begins. Unsure yet if it should include retries because really that’s more or less the same as the client being offline (which is not included).

**Comment by orborde** [comment]
We use the protobuf binary format for this message type on the wire, so it's trivial to change the name later (the wire format won't change as long as we don't change the field number).

Since this is easy to change and since it sounds like nobody has a strongly favored better option, how about we merge this as-is for now?

**Comment by BrandonArp** [comment]
How about request_millis_since_epoch? Changing the name involves changing people's code. It's not breaking on the wire, but it absolutely is in the library.

**Comment by orborde** [comment]
Updated. Take another look?

**Review by BrandonArp — APPROVED** [review]

**Pull request merged**
